//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace WLSCU.HRW {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LayDanhSachTheoNgayOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNhanDuLieuOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateKetQuaOperationCompleted;
        
        private System.Threading.SendOrPostCallback HuyKetQuaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WLSCU.Properties.Settings.Default.VIETBAIT_HRS_HRW_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LayDanhSachTheoNgayCompletedEventHandler LayDanhSachTheoNgayCompleted;
        
        /// <remarks/>
        public event UpdateNhanDuLieuCompletedEventHandler UpdateNhanDuLieuCompleted;
        
        /// <remarks/>
        public event UpdateKetQuaCompletedEventHandler UpdateKetQuaCompleted;
        
        /// <remarks/>
        public event HuyKetQuaCompletedEventHandler HuyKetQuaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachTheoNgay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LayDanhSachTheoNgay(string tungay, string denngay, string patientcode, string sophieu, int IsLayLai, string ServiceCode) {
            object[] results = this.Invoke("LayDanhSachTheoNgay", new object[] {
                        tungay,
                        denngay,
                        patientcode,
                        sophieu,
                        IsLayLai,
                        ServiceCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachTheoNgayAsync(string tungay, string denngay, string patientcode, string sophieu, int IsLayLai, string ServiceCode) {
            this.LayDanhSachTheoNgayAsync(tungay, denngay, patientcode, sophieu, IsLayLai, ServiceCode, null);
        }
        
        /// <remarks/>
        public void LayDanhSachTheoNgayAsync(string tungay, string denngay, string patientcode, string sophieu, int IsLayLai, string ServiceCode, object userState) {
            if ((this.LayDanhSachTheoNgayOperationCompleted == null)) {
                this.LayDanhSachTheoNgayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachTheoNgayOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachTheoNgay", new object[] {
                        tungay,
                        denngay,
                        patientcode,
                        sophieu,
                        IsLayLai,
                        ServiceCode}, this.LayDanhSachTheoNgayOperationCompleted, userState);
        }
        
        private void OnLayDanhSachTheoNgayOperationCompleted(object arg) {
            if ((this.LayDanhSachTheoNgayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachTheoNgayCompleted(this, new LayDanhSachTheoNgayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateNhanDuLieu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateNhanDuLieu(int idchidinhCT) {
            object[] results = this.Invoke("UpdateNhanDuLieu", new object[] {
                        idchidinhCT});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateNhanDuLieuAsync(int idchidinhCT) {
            this.UpdateNhanDuLieuAsync(idchidinhCT, null);
        }
        
        /// <remarks/>
        public void UpdateNhanDuLieuAsync(int idchidinhCT, object userState) {
            if ((this.UpdateNhanDuLieuOperationCompleted == null)) {
                this.UpdateNhanDuLieuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNhanDuLieuOperationCompleted);
            }
            this.InvokeAsync("UpdateNhanDuLieu", new object[] {
                        idchidinhCT}, this.UpdateNhanDuLieuOperationCompleted, userState);
        }
        
        private void OnUpdateNhanDuLieuOperationCompleted(object arg) {
            if ((this.UpdateNhanDuLieuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNhanDuLieuCompleted(this, new UpdateNhanDuLieuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateKetQua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateKetQua(int sophieu, string vungks, string mota, string ketluan, string ngayxacnhan, string bsthuchien, bool DaKetQua) {
            object[] results = this.Invoke("UpdateKetQua", new object[] {
                        sophieu,
                        vungks,
                        mota,
                        ketluan,
                        ngayxacnhan,
                        bsthuchien,
                        DaKetQua});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateKetQuaAsync(int sophieu, string vungks, string mota, string ketluan, string ngayxacnhan, string bsthuchien, bool DaKetQua) {
            this.UpdateKetQuaAsync(sophieu, vungks, mota, ketluan, ngayxacnhan, bsthuchien, DaKetQua, null);
        }
        
        /// <remarks/>
        public void UpdateKetQuaAsync(int sophieu, string vungks, string mota, string ketluan, string ngayxacnhan, string bsthuchien, bool DaKetQua, object userState) {
            if ((this.UpdateKetQuaOperationCompleted == null)) {
                this.UpdateKetQuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateKetQuaOperationCompleted);
            }
            this.InvokeAsync("UpdateKetQua", new object[] {
                        sophieu,
                        vungks,
                        mota,
                        ketluan,
                        ngayxacnhan,
                        bsthuchien,
                        DaKetQua}, this.UpdateKetQuaOperationCompleted, userState);
        }
        
        private void OnUpdateKetQuaOperationCompleted(object arg) {
            if ((this.UpdateKetQuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateKetQuaCompleted(this, new UpdateKetQuaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HuyKetQua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HuyKetQua(int sophieu) {
            object[] results = this.Invoke("HuyKetQua", new object[] {
                        sophieu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HuyKetQuaAsync(int sophieu) {
            this.HuyKetQuaAsync(sophieu, null);
        }
        
        /// <remarks/>
        public void HuyKetQuaAsync(int sophieu, object userState) {
            if ((this.HuyKetQuaOperationCompleted == null)) {
                this.HuyKetQuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHuyKetQuaOperationCompleted);
            }
            this.InvokeAsync("HuyKetQua", new object[] {
                        sophieu}, this.HuyKetQuaOperationCompleted, userState);
        }
        
        private void OnHuyKetQuaOperationCompleted(object arg) {
            if ((this.HuyKetQuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HuyKetQuaCompleted(this, new HuyKetQuaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LayDanhSachTheoNgayCompletedEventHandler(object sender, LayDanhSachTheoNgayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachTheoNgayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachTheoNgayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateNhanDuLieuCompletedEventHandler(object sender, UpdateNhanDuLieuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateNhanDuLieuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateNhanDuLieuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateKetQuaCompletedEventHandler(object sender, UpdateKetQuaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateKetQuaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateKetQuaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HuyKetQuaCompletedEventHandler(object sender, HuyKetQuaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HuyKetQuaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HuyKetQuaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591